source("~/proteinevoutk20/pkg/R/hessian.R") 
 trees <- read.tree("~/proteinevoutk20/pkg/R/simtrees.tre") 
 start_seq=sample(20,500,replace=T) 
 op_seq=rep(1,500) 
 system.time(sim <- simTree(trees[[4]],500,op_seq,20,0.9,Nu_vec,alpha=al,beta=be,gamma=ga,rootseq=start_seq, ancestral=TRUE)) 
 system.time(mle_log_op <- MLE_sw_log(c(-2,-1,-8),trees[[4]],sim[1:8,],m=20,al,mumat,protein_op=op_seq,root=start_seq,trace=1)) 
 hes_op <- find_hessian_log(mle_log$par,trees[[4]],sim[1:8,],al,mumat,20,protein_op=op_seq,root=start_seq) 
 system.time(mle_log_nop <- MLE_sw_log(c(-2,-1,-8),trees[[4]],sim[1:8,],m=20,al,mumat,trace=1)) 
 hes_nop <- find_hessian_log(mle_log_nop$par,trees[[4]],sim[1:8,],al,mumat,20) 
 save.image(file="op_simu_4_500_0.9.RData",compress=TRUE) 
