source("~/proteinevoutk20/pkg/R/hessian.R") 
 trees <- read.tree("~/proteinevoutk20/pkg/R/simtrees_correct.tre") 
 start_seq=sample(20,300,replace=T) 
 op_seq=rep(1,300) 
 system.time(sim <- simTree(trees[[11]],300,op_seq,20,0.3,Nu_vec,alpha=al,beta=be,gamma=ga,rootseq=start_seq, ancestral=TRUE)) 
 system.time(mle_log_op <- MLE_sw_log(c(-2,-1,-8),trees[[11]],sim[1:16,],m=20,al,mumat,protein_op=op_seq,root=start_seq,trace=1)) 
 hes_op <- find_hessian_log(mle_log_op$par,trees[[11]],sim[1:16,],al,mumat,20,protein_op=op_seq,root=start_seq) 
 system.time(mle_log_nop <- MLE_sw_log(c(-2,-1,-8),trees[[11]],sim[1:16,],m=20,al,mumat,trace=1)) 
 hes_nop <- find_hessian_log(mle_log_nop$par,trees[[11]],sim[1:16,],al,mumat,20) 
 save.image(file="op_simu_15_300_0.3.RData",compress=TRUE) 
