source("~/proteinevoutk20/pkg/R/hessian.R") 
 trees <- read.tree("~/proteinevoutk20/pkg/R/simtrees.tre") 
 start_seq=sample(20,1000,replace=T) 
 op_seq=rep(1,1000) 
 system.time(sim <- simTree(trees[[3]],1000,op_seq,20,0.3,Nu_vec,alpha=al,beta=be,gamma=ga,rootseq=start_seq, ancestral=TRUE)) 
 system.time(mle_log_op <- MLE_sw_log(c(-2,-1,-8),trees[[3]],sim[1:8,],m=20,al,mumat,protein_op=op_seq,root=start_seq,trace=1)) 
 hes_op <- find_hessian_log(mle_log$par,trees[[3]],sim[1:8,],al,mumat,20,protein_op=op_seq,root=start_seq) 
 system.time(mle_log_nop <- MLE_sw_log(c(-2,-1,-8),trees[[3]],sim[1:8,],m=20,al,mumat,trace=1)) 
 hes_nop <- find_hessian_log(mle_log_nop$par,trees[[3]],sim[1:8,],al,mumat,20) 
 save.image(file="op_simu_3_1000_0.3.RData",compress=TRUE) 
