#true.phi<-runif(106, min=min(rokasPhi$SEMPPR, na.rm=TRUE), max=max(rokasPhi$SEMPPR, na.rm=TRUE))
true.phi <- rlnorm(100,mean(phidata$SEMPPR),sd(phidata$SEMPPR)) # random samples from log normal distribution
gphi<-abs(rnorm(length(true.phi), 2*true.phi, 0.001))
print(range(true.phi))
print(range(gphi))
phi.sd <- 0.01
phi1<-abs(rnorm(length(true.phi), true.phi, phi.sd))
phi2<-abs(rnorm(length(true.phi), true.phi, phi.sd))
phi3<-abs(rnorm(length(true.phi), true.phi, phi.sd))
mkp.data <- data.frame(Beyer=log(phi1),SEMPPR=log(phi2),Ing=log(phi3),lgphi=log(gphi))
pairs(mkp.data)
phidata.lm(mkp.data)
# mkp.data$Beyer <- log(phi1)
# mkp.data$SEMPPR <- log(phi2)
# mkp.data$Ing <- log(phi3)
# mkp.data$lgphi <- log(gphi)
#plot(gphi, true.phi)
bad.phi<-abs(rnorm(length(true.phi), true.phi, 1))
awful.phi<-runif(100,min=exp(min(cphi$SEMPPR)),max=exp(max(cphi$SEMPPR)))
#plot(true.phi, bad.phi)
par(mfrow=c(2,3))
phi.range<-range(c(true.phi, bad.phi, awful.phi))
g.range<-range(c(gphi/true.phi, gphi/bad.phi, gphi/awful.phi))
plot(true.phi, gphi, xlim=phi.range)
plot(bad.phi, gphi, xlim=phi.range)
plot(awful.phi, gphi, xlim=phi.range)
plot(true.phi, gphi/true.phi, xlim=phi.range, ylim=g.range, log="y")
plot(bad.phi, gphi/bad.phi, xlim=phi.range, ylim=g.range, log="y")
plot(awful.phi, gphi/awful.phi, xlim=phi.range, ylim=g.range, log="y")

plot(true.phi, gphi)
plot(bad.phi, gphi)
plot(awful.phi, gphi)
plot(true.phi, gphi/true.phi, log="y")
plot(bad.phi, gphi/bad.phi, log="y")
plot(awful.phi, gphi/awful.phi,log="y")
#plot(true.phi, gphi)