true.phi<-runif(106, min=min(rokasPhi$SEMPPR, na.rm=TRUE), max=max(rokasPhi$SEMPPR, na.rm=TRUE))
gphi<-abs(rnorm(length(true.phi), 10*true.phi, 0.1))
print(range(true.phi))
print(range(gphi))
#plot(gphi, true.phi)
bad.phi<-abs(rnorm(length(true.phi), true.phi, 0.1))
awful.phi<-runif(106)
#plot(true.phi, bad.phi)
par(mfrow=c(2,3))
phi.range<-range(c(true.phi, bad.phi, awful.phi))
g.range<-range(c(gphi/true.phi, gphi/bad.phi, gphi/awful.phi))
plot(true.phi, gphi, xlim=phi.range)
plot(bad.phi, gphi, xlim=phi.range)
plot(awful.phi, gphi, xlim=phi.range)
plot(true.phi, gphi/true.phi, xlim=phi.range, ylim=g.range, log="y")
plot(bad.phi, gphi/bad.phi, xlim=phi.range, ylim=g.range, log="y")
plot(awful.phi, gphi/awful.phi, xlim=phi.range, ylim=g.range, log="y")
#plot(true.phi, gphi)